export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // app
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EXPIRED_CONFIRMATION_CODE = 'EXPIRED_CONFIRMATION_CODE',

  // http
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}
