export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // app
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',

  // http
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}
